site_name: gREST
pages:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - Application: application.md
  - Authentication & Authorization: authentication_authorization.md
  - Views: views.md
  - Routes: routes.md
  - Models: models.md
  - Configuration: configuration.md
  - Custom Endpoints: custom_endpoints.md
  - Deployment: deployment.md
  - License: license.md
  - About: about.md
theme:
  name: material
  palette:
    primary: 'Blue Grey'
    accent: 'Amber'
  logo: 'img/gREST-logo.png'
markdown_extensions:
  - fenced_code